/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package perpustakaanprakpro;

/**
 *
 * @author Naufal
 */
public class mainPerpus extends javax.swing.JFrame {

    /**
     * Creates new form mainPerpus
     */
    public mainPerpus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HalamanPeminjaman = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        PeminjamanTitle = new javax.swing.JLabel();
        InputNamaPeminjam = new javax.swing.JTextField();
        NamaPeminjamLabel = new javax.swing.JLabel();
        NimPeminjamLabel = new javax.swing.JLabel();
        KodeBukuLabel = new javax.swing.JLabel();
        JudulBukuLabel = new javax.swing.JLabel();
        TanggalPinjamLabel = new javax.swing.JLabel();
        TanggalKembaliLabel = new javax.swing.JLabel();
        InputNimPeminjam = new javax.swing.JTextField();
        InputKodeBuku = new javax.swing.JTextField();
        InputJudulBuku = new javax.swing.JTextField();
        InputTanggalPinjam = new javax.swing.JTextField();
        InputTanggalKembali = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        HalamanPengembalian = new javax.swing.JDialog();
        HalamanDataBuku = new javax.swing.JDialog();
        HalamanDataAnggota = new javax.swing.JDialog();
        MainPanel = new javax.swing.JPanel();
        mainJudul = new javax.swing.JLabel();
        pengembalianButton = new javax.swing.JButton();
        peminjamanButton = new javax.swing.JButton();
        bukuButton = new javax.swing.JButton();
        anggotaButton = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        PeminjamanTitle.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        PeminjamanTitle.setForeground(new java.awt.Color(255, 255, 255));
        PeminjamanTitle.setText("Peminjaman Buku");

        InputNamaPeminjam.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N

        NamaPeminjamLabel.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        NamaPeminjamLabel.setText("Nama :");

        NimPeminjamLabel.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        NimPeminjamLabel.setText("Nim :");

        KodeBukuLabel.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        KodeBukuLabel.setText("Kode Buku :");

        JudulBukuLabel.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        JudulBukuLabel.setText("Judul Buku :");

        TanggalPinjamLabel.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        TanggalPinjamLabel.setText("Tanggal Pinjam :");

        TanggalKembaliLabel.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        TanggalKembaliLabel.setText("Tanggal Kembali :");

        InputNimPeminjam.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        InputNimPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNimPeminjamActionPerformed(evt);
            }
        });

        InputKodeBuku.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        InputKodeBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputKodeBukuActionPerformed(evt);
            }
        });

        InputJudulBuku.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        InputJudulBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputJudulBukuActionPerformed(evt);
            }
        });

        InputTanggalPinjam.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        InputTanggalPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputTanggalPinjamActionPerformed(evt);
            }
        });

        InputTanggalKembali.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        InputTanggalKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputTanggalKembaliActionPerformed(evt);
            }
        });

        SubmitButton.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        SubmitButton.setText("Submit");

        ResetButton.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NimPeminjamLabel)
                            .addComponent(KodeBukuLabel)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TanggalKembaliLabel)
                                    .addComponent(JudulBukuLabel)
                                    .addComponent(TanggalPinjamLabel))
                                .addGap(63, 63, 63)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(InputKodeBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(InputTanggalPinjam, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(InputJudulBuku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(InputTanggalKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(InputNamaPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(InputNimPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(ResetButton)
                                .addGap(18, 18, 18)
                                .addComponent(SubmitButton)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(NamaPeminjamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(698, 698, 698))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(PeminjamanTitle)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(PeminjamanTitle)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InputNamaPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NamaPeminjamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InputNimPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NimPeminjamLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(KodeBukuLabel)
                            .addComponent(InputKodeBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InputJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JudulBukuLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InputTanggalPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TanggalPinjamLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TanggalKembaliLabel)
                            .addComponent(InputTanggalKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)))
                .addGap(119, 119, 119))
        );

        javax.swing.GroupLayout HalamanPeminjamanLayout = new javax.swing.GroupLayout(HalamanPeminjaman.getContentPane());
        HalamanPeminjaman.getContentPane().setLayout(HalamanPeminjamanLayout);
        HalamanPeminjamanLayout.setHorizontalGroup(
            HalamanPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        HalamanPeminjamanLayout.setVerticalGroup(
            HalamanPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HalamanPengembalianLayout = new javax.swing.GroupLayout(HalamanPengembalian.getContentPane());
        HalamanPengembalian.getContentPane().setLayout(HalamanPengembalianLayout);
        HalamanPengembalianLayout.setHorizontalGroup(
            HalamanPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        HalamanPengembalianLayout.setVerticalGroup(
            HalamanPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HalamanDataBukuLayout = new javax.swing.GroupLayout(HalamanDataBuku.getContentPane());
        HalamanDataBuku.getContentPane().setLayout(HalamanDataBukuLayout);
        HalamanDataBukuLayout.setHorizontalGroup(
            HalamanDataBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        HalamanDataBukuLayout.setVerticalGroup(
            HalamanDataBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HalamanDataAnggotaLayout = new javax.swing.GroupLayout(HalamanDataAnggota.getContentPane());
        HalamanDataAnggota.getContentPane().setLayout(HalamanDataAnggotaLayout);
        HalamanDataAnggotaLayout.setHorizontalGroup(
            HalamanDataAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        HalamanDataAnggotaLayout.setVerticalGroup(
            HalamanDataAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(0, 204, 204));

        mainJudul.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        mainJudul.setForeground(new java.awt.Color(0, 0, 0));
        mainJudul.setText("LIBRARY");

        pengembalianButton.setBackground(new java.awt.Color(0, 0, 0));
        pengembalianButton.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        pengembalianButton.setForeground(new java.awt.Color(255, 255, 255));
        pengembalianButton.setText("Pengembalian Buku");
        pengembalianButton.setBorder(null);
        pengembalianButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pengembalianButton.setMargin(new java.awt.Insets(14, 14, 14, 14));
        pengembalianButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengembalianButtonActionPerformed(evt);
            }
        });

        peminjamanButton.setBackground(new java.awt.Color(0, 0, 0));
        peminjamanButton.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        peminjamanButton.setForeground(new java.awt.Color(255, 255, 255));
        peminjamanButton.setText("Peminjaman Buku");
        peminjamanButton.setBorder(null);
        peminjamanButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        peminjamanButton.setMargin(new java.awt.Insets(14, 14, 14, 14));
        peminjamanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peminjamanButtonActionPerformed(evt);
            }
        });

        bukuButton.setBackground(new java.awt.Color(0, 0, 0));
        bukuButton.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        bukuButton.setForeground(new java.awt.Color(255, 255, 255));
        bukuButton.setText("Data Buku");
        bukuButton.setBorder(null);
        bukuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bukuButton.setMargin(new java.awt.Insets(14, 14, 14, 14));
        bukuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bukuButtonActionPerformed(evt);
            }
        });

        anggotaButton.setBackground(new java.awt.Color(0, 0, 0));
        anggotaButton.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        anggotaButton.setForeground(new java.awt.Color(255, 255, 255));
        anggotaButton.setText("Data Anggota");
        anggotaButton.setBorder(null);
        anggotaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        anggotaButton.setMargin(new java.awt.Insets(14, 14, 14, 14));
        anggotaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anggotaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(anggotaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bukuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peminjamanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainPanelLayout.createSequentialGroup()
                            .addGap(304, 304, 304)
                            .addComponent(mainJudul))
                        .addGroup(MainPanelLayout.createSequentialGroup()
                            .addGap(260, 260, 260)
                            .addComponent(pengembalianButton, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(mainJudul)
                .addGap(37, 37, 37)
                .addComponent(peminjamanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(pengembalianButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(bukuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(anggotaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pengembalianButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengembalianButtonActionPerformed
        // TODO add your handling code here:
        this.HalamanPengembalian.setVisible(true);
        this.HalamanPengembalian.setSize(800, 400);
    }//GEN-LAST:event_pengembalianButtonActionPerformed

    private void peminjamanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peminjamanButtonActionPerformed
        // TODO add your handling code here:
        this.HalamanPeminjaman.setVisible(true);
        this.HalamanPeminjaman.setSize(800, 400);
    }//GEN-LAST:event_peminjamanButtonActionPerformed

    private void bukuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bukuButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bukuButtonActionPerformed

    private void anggotaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anggotaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anggotaButtonActionPerformed

    private void InputNimPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNimPeminjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNimPeminjamActionPerformed

    private void InputKodeBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputKodeBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputKodeBukuActionPerformed

    private void InputJudulBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputJudulBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputJudulBukuActionPerformed

    private void InputTanggalPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputTanggalPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputTanggalPinjamActionPerformed

    private void InputTanggalKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputTanggalKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputTanggalKembaliActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainPerpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainPerpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainPerpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainPerpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainPerpus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog HalamanDataAnggota;
    private javax.swing.JDialog HalamanDataBuku;
    private javax.swing.JDialog HalamanPeminjaman;
    private javax.swing.JDialog HalamanPengembalian;
    private javax.swing.JTextField InputJudulBuku;
    private javax.swing.JTextField InputKodeBuku;
    private javax.swing.JTextField InputNamaPeminjam;
    private javax.swing.JTextField InputNimPeminjam;
    private javax.swing.JTextField InputTanggalKembali;
    private javax.swing.JTextField InputTanggalPinjam;
    private javax.swing.JLabel JudulBukuLabel;
    private javax.swing.JLabel KodeBukuLabel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel NamaPeminjamLabel;
    private javax.swing.JLabel NimPeminjamLabel;
    private javax.swing.JLabel PeminjamanTitle;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel TanggalKembaliLabel;
    private javax.swing.JLabel TanggalPinjamLabel;
    private javax.swing.JButton anggotaButton;
    private javax.swing.JButton bukuButton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mainJudul;
    private javax.swing.JButton peminjamanButton;
    private javax.swing.JButton pengembalianButton;
    // End of variables declaration//GEN-END:variables
}
